###
GET localhost:8080/persons/by-city?city=MOSCOW

###
GET localhost:8080/persons/by-city?city=sochi

###
GET localhost:8080/persons/by-age?age=30

###
GET localhost:8080/persons/by-name-surname?name=Ivan&surname=Ivanov

###
GET localhost:8080/persons/by-name-surname?name=Andrey&surname=S

###
GET localhost:8080/persons/by-name-surname?name=sergey&surname=aleksandrov

###
GET localhost:8080/persons/hello?username=Admin